from ArvoreBuscaBinaria import ArvoreBuscaBinaria

arvore = ArvoreBuscaBinaria()
arvore.inserir(50, arvore.raiz)
arvore.inserir(30, arvore.raiz)
arvore.inserir(25, arvore.raiz)
arvore.inserir(40, arvore.raiz)
arvore.inserir(35, arvore.raiz)
arvore.inserir(38, arvore.raiz)
arvore.inserir(39, arvore.raiz)
arvore.inserir(45, arvore.raiz)
arvore.inserir(80, arvore.raiz)
arvore.inserir(70, arvore.raiz)
arvore.inserir(75, arvore.raiz)
arvore.inserir(85, arvore.raiz)
arvore.inserir(84, arvore.raiz)
arvore.inserir(86, arvore.raiz)


print('---Impressao:')
print('Pre-ordem:')
arvore.imprimir('pre', arvore.raiz)
print('\nOrdem:')
arvore.imprimir('ord', arvore.raiz)
print('\nPos-ordem:')
arvore.imprimir('pos', arvore.raiz)
print('\nMinimo:')
print(arvore.minimo(arvore.raiz).chave)
print('Maximo:')
print(arvore.maximo(arvore.raiz).chave)
# print('---Funcao Sucessor:')
# print(arvore.sucessor(arvore.raiz).chave)
# print('---Predecessor:')
# print(arvore.predecessor(arvore.raiz).chave)
# print('---Buscar:')
# print(arvore.buscar(5, arvore.raiz).chave)
print('---Remocao:')
# arvore.remover(30, arvore.raiz)
# arvore.remover(40, arvore.raiz)
print('Sucessor:')
print(arvore.sucessor(arvore.buscar(40, arvore.raiz)).chave)


print('---Impressao:')
print('ordem:')
arvore.imprimir('ord', arvore.raiz)